#!/bin/bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Running post deploy"
COMMAND=$(cat <<EOF
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)

# /etc/init.d/clamav-daemon start
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
